In [3]:
import numpy as ny
a = ny.ones((5,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
b = ny.arange(1,17)
print(b)
b = b.reshape((4,4))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [15]:
import pandas as pd
fruits = ["蘋果", "橘子", "梨子"]
quanities = [15, 33, 45]
s = pd.Series(quanities, index=fruits)
print(s)

蘋果    15
橘子    33
梨子    45
dtype: int64


In [17]:
print(s["橘子"], ["梨子"])

33 ['梨子']


In [19]:
print(s[["橘子", "梨子"]])

橘子    33
梨子    45
dtype: int64


In [24]:
print(s["橘子"], s["梨子"])

33 45


In [25]:
print(s[["橘子"]], s[["梨子"]])

橘子    33
dtype: int64 梨子    45
dtype: int64


In [42]:
a = [1, 2, 3, 4]
print(a[2])
print(a[0],a[3])
print(a[0: 1])
a[4] = int(5)
print(a)

3
1 4
[1]


IndexError: list assignment index out of range

In [29]:
fruit = {"蘋果":[4, 3, 1, 0], "香蕉":[0, 4, 6, 2], "橘子":[1, 5, 2, 4]}
fruit_table = pd.DataFrame(fruit)
print(fruit_table)

   蘋果  香蕉  橘子
0   4   0   1
1   3   4   5
2   1   6   2
3   0   2   4


In [37]:
for index, row in fruit_table.iterrows():
    ### print(index)
    ### print(row)
    print(index, row["蘋果"], row["香蕉"], row["橘子"])

0 4 0 1
1 3 4 5
2 1 6 2
3 0 2 4


In [41]:
for index in fruit_table.iterrows():
    ### print(index)
    ### print(row)
    print(index)

(0, 蘋果    4
香蕉    0
橘子    1
Name: 0, dtype: int64)
(1, 蘋果    3
香蕉    4
橘子    5
Name: 1, dtype: int64)
(2, 蘋果    1
香蕉    6
橘子    2
Name: 2, dtype: int64)
(3, 蘋果    0
香蕉    2
橘子    4
Name: 3, dtype: int64)


In [4]:
L = ny.array([3, -2, -1, 5, 7, -3])
A = L > 0
A

array([ True, False, False,  True,  True, False])